/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_api_v1_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/invitations/inspect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inspect Invitation */
        post: operations["inspect_invitation_api_v1_auth_invitations_inspect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/invitations/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept Invitation */
        post: operations["accept_invitation_api_v1_auth_invitations_accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password-reset/inspect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inspect Reset */
        post: operations["inspect_reset_api_v1_auth_password_reset_inspect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password-reset/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Reset */
        post: operations["confirm_reset_api_v1_auth_password_reset_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_api_v1_me_get"];
        put?: never;
        post?: never;
        /** Delete Me */
        delete: operations["delete_me_api_v1_me_delete"];
        options?: never;
        head?: never;
        /** Patch Me */
        patch: operations["patch_me_api_v1_me_patch"];
        trace?: never;
    };
    "/api/v1/me/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Me */
        get: operations["export_me_api_v1_me_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin List Users */
        get: operations["admin_list_users_api_v1_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin Invite */
        post: operations["admin_invite_api_v1_admin_invitations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}/reset-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin Reset Link */
        post: operations["admin_reset_link_api_v1_admin_users__user_id__reset_link_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}/revoke-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin Revoke Sessions */
        post: operations["admin_revoke_sessions_api_v1_admin_users__user_id__revoke_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Admin Patch User */
        patch: operations["admin_patch_user_api_v1_admin_users__user_id__patch"];
        trace?: never;
    };
    "/api/v1/content-reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report */
        post: operations["report_api_v1_content_reports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/learning-paths": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Paths */
        get: operations["list_paths_api_v1_learning_paths_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/learning-paths/{path_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Path Detail */
        get: operations["path_detail_api_v1_learning_paths__path_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lessons/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lesson */
        get: operations["lesson_api_v1_lessons__item_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scenario */
        get: operations["scenario_api_v1_scenarios__item_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/aids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Serve Aid */
        post: operations["serve_aid_api_v1_aids_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Attempt */
        post: operations["submit_attempt_api_v1_attempts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attempts/{attempt_id}/self-assessment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Self Assess */
        post: operations["self_assess_api_v1_attempts__attempt_id__self_assessment_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attempts/{attempt_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Attempt */
        get: operations["get_attempt_api_v1_attempts__attempt_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Attempts */
        get: operations["my_attempts_api_v1_me_attempts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/content/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Revisions */
        get: operations["list_revisions_api_v1_admin_content_revisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/content/units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Units */
        get: operations["list_units_api_v1_admin_content_units_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/content/revisions/{revision_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Revision Detail */
        get: operations["revision_detail_api_v1_admin_content_revisions__revision_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/content/revisions/{revision_id}/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Finding */
        post: operations["add_finding_api_v1_admin_content_revisions__revision_id__findings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/content/findings/{finding_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Finding */
        patch: operations["update_finding_api_v1_admin_content_findings__finding_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/content/revisions/{revision_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve */
        post: operations["approve_api_v1_admin_content_revisions__revision_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/content/revisions/{revision_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish */
        post: operations["publish_api_v1_admin_content_revisions__revision_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/content/units/{unit_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish Unit */
        post: operations["publish_unit_api_v1_admin_content_units__unit_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/content/revisions/{revision_id}/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Withdraw */
        post: operations["withdraw_api_v1_admin_content_revisions__revision_id__withdraw_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcceptInvitationIn */
        AcceptInvitationIn: {
            /** Token */
            token: string;
            /** Password */
            password: string;
            /** Password Confirm */
            password_confirm: string;
            /** Accept Privacy */
            accept_privacy: boolean;
            /** Consent Version */
            consent_version: string;
            /** Adult */
            adult: boolean;
            /** Display Name */
            display_name?: string | null;
        };
        /** AdminInvitationIn */
        AdminInvitationIn: {
            /** Email */
            email: string;
        };
        /** AdminUnitOut */
        AdminUnitOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Position */
            position: number;
        };
        /** AdminUserOut */
        AdminUserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /**
             * Role
             * @enum {string}
             */
            role: "student" | "admin";
            /** Display Name */
            display_name: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Login At */
            last_login_at: string | null;
            /** Is Internal */
            is_internal: boolean;
            /** Onboarded */
            onboarded: boolean;
            /** Active Sessions */
            active_sessions: number;
        };
        /** AdminUserPatch */
        AdminUserPatch: {
            /** Is Internal */
            is_internal: boolean;
        };
        /** AidContentOut */
        AidContentOut: {
            /** Kind */
            kind: string;
            /** Index */
            index: number;
            /** Content */
            content: string;
            /** Remaining */
            remaining: number;
        };
        /** AidIn */
        AidIn: {
            /**
             * Activity Id
             * Format: uuid
             */
            activity_id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "hint" | "support_es" | "transcript" | "example";
            /**
             * Index
             * @default 0
             */
            index: number;
        };
        /** AidOut */
        AidOut: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "hint" | "support_es" | "transcript" | "example";
            /** Count */
            count: number;
        };
        /** ApproveIn */
        ApproveIn: {
            /** Content Hash */
            content_hash: string;
            /** Note */
            note?: string | null;
        };
        /** AttemptDetailOut */
        AttemptDetailOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Activity Id
             * Format: uuid
             */
            activity_id: string;
            /** Response */
            response: {
                [key: string]: unknown;
            };
            /** Evaluation Status */
            evaluation_status: string;
            /** Score */
            score: number | null;
            /** Correct */
            correct: boolean | null;
            /** Result */
            result: {
                [key: string]: unknown;
            };
            /** Aided */
            aided: boolean;
            /** Submitted At */
            submitted_at: string;
            /** Mode */
            mode?: string | null;
            feedback: components["schemas"]["AttemptFeedbackOut"];
        };
        /** AttemptFeedbackOut */
        AttemptFeedbackOut: {
            /** Explanation */
            explanation?: string | null;
            /** Model Answer */
            model_answer?: string | null;
            /** Model Commentary Es */
            model_commentary_es?: string | null;
            /** Target Sentence */
            target_sentence?: string | null;
            /** Rubric */
            rubric?: {
                [key: string]: unknown;
            } | null;
        };
        /** AttemptIn */
        AttemptIn: {
            /**
             * Activity Id
             * Format: uuid
             */
            activity_id: string;
            /** Response */
            response: {
                [key: string]: unknown;
            };
            /** Revision Of */
            revision_of?: string | null;
            /**
             * Audio Plays
             * @default 0
             */
            audio_plays: number;
        };
        /** AttemptOut */
        AttemptOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Activity Id
             * Format: uuid
             */
            activity_id: string;
            /**
             * Revision Id
             * Format: uuid
             */
            revision_id: string;
            /** Mode */
            mode: string;
            /** Evaluation Status */
            evaluation_status: string;
            /** Evaluation Source */
            evaluation_source: string;
            /** Score */
            score: number | null;
            /** Correct */
            correct: boolean | null;
            /** Result */
            result: {
                [key: string]: unknown;
            };
            /** Aided */
            aided: boolean;
            /** First Attempt */
            first_attempt: boolean;
            /** Submitted At */
            submitted_at: string;
            feedback: components["schemas"]["AttemptFeedbackOut"];
            /** Lesson Completed */
            lesson_completed: boolean | null;
            /** Review Objectives */
            review_objectives: string[];
        };
        /** AttemptSummaryOut */
        AttemptSummaryOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Activity Id
             * Format: uuid
             */
            activity_id: string;
            /** Response */
            response: {
                [key: string]: unknown;
            };
            /** Evaluation Status */
            evaluation_status: string;
            /** Score */
            score: number | null;
            /** Correct */
            correct: boolean | null;
            /** Result */
            result: {
                [key: string]: unknown;
            };
            /** Aided */
            aided: boolean;
            /** Submitted At */
            submitted_at: string;
            /** Mode */
            mode?: string | null;
        };
        /** ContentReportIn */
        ContentReportIn: {
            /**
             * Revision Id
             * Format: uuid
             */
            revision_id: string;
            /** Activity Id */
            activity_id?: string | null;
            /** Attempt Id */
            attempt_id?: string | null;
            /**
             * Category
             * @enum {string}
             */
            category: "answer_key" | "unclear" | "audio" | "typo" | "other";
            /**
             * Message
             * @default
             */
            message: string;
            /** Page */
            page?: string | null;
        };
        /** CreatedOut */
        CreatedOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** DeleteMeIn */
        DeleteMeIn: {
            /** Password */
            password: string;
        };
        /** FindingIn */
        FindingIn: {
            /** Category */
            category: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "material" | "minor";
            /** Description */
            description: string;
        };
        /** FindingOut */
        FindingOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Author */
            author: string;
            /** Category */
            category: string;
            /** Severity */
            severity: string;
            /** Description */
            description: string;
            /** Status */
            status: string;
            /** Resolution Note */
            resolution_note: string | null;
            /** Created At */
            created_at: string;
            /** Resolved At */
            resolved_at: string | null;
        };
        /** FindingPatch */
        FindingPatch: {
            /**
             * Status
             * @enum {string}
             */
            status: "open" | "resolved" | "wont_fix";
            /** Resolution Note */
            resolution_note?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Status */
            status: string;
        };
        /** InvitationInfoOut */
        InvitationInfoOut: {
            /** Email */
            email: string;
            /** Consent Version */
            consent_version: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** ItemStateRefOut */
        ItemStateRefOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Position */
            position: number;
            /** Skill */
            skill: string | null;
            /** Form Kind */
            form_kind: string | null;
            /**
             * State
             * @enum {string}
             */
            state: "not_started" | "in_progress" | "completed";
        };
        /** LessonOut */
        LessonOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Revision Id
             * Format: uuid
             */
            revision_id: string;
            /** Revision Version */
            revision_version: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "lesson" | "scenario" | "assessment_form";
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            unit: components["schemas"]["UnitRefOut"] | null;
            /** Objectives */
            objectives: string[];
            /** Activities */
            activities: components["schemas"]["StudentActivityOut"][];
            /** Skill */
            skill?: string | null;
            /** Objective Es */
            objective_es?: string | null;
            pcre?: components["schemas"]["PcreOut"] | null;
            /** Application Task Es */
            application_task_es?: string | null;
            /** Passages */
            passages?: components["schemas"]["PassageOut"][];
            /** Situation Es */
            situation_es?: string | null;
            /** Situation En */
            situation_en?: string | null;
            /** Learner Role En */
            learner_role_en?: string | null;
            /** Opening En */
            opening_en?: string | null;
            /** Required Moves */
            required_moves?: string[];
            /** Max Seconds */
            max_seconds?: number | null;
            /** Form Kind */
            form_kind?: string | null;
            /** Duration Minutes */
            duration_minutes?: number | null;
            /** Last Attempts */
            last_attempts: {
                [key: string]: components["schemas"]["AttemptSummaryOut"];
            };
            /** Notice */
            notice: string | null;
            progress: components["schemas"]["ProgressOut"];
        };
        /** LinkOut */
        LinkOut: {
            /** Url */
            url: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** LoginIn */
        LoginIn: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** MeOut */
        MeOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /**
             * Role
             * @enum {string}
             */
            role: "student" | "admin";
            /** Display Name */
            display_name: string | null;
            /** Timezone */
            timezone: string;
            /** Goal Purpose */
            goal_purpose: ("work" | "studies" | "certification" | "other" | "unknown") | null;
            /** Target Exam */
            target_exam: ("toefl_ibt" | "ielts_academic" | "cambridge_b2_first" | "toefl_itp" | "other" | "unknown") | null;
            /** Target Exam Other */
            target_exam_other: string | null;
            /** Target Score */
            target_score: string | null;
            /** Target Date */
            target_date: string | null;
            /** Self Reported Level */
            self_reported_level: ("A2" | "B1" | "B2" | "unknown") | null;
            /** Onboarded */
            onboarded: boolean;
            /** Consent Version */
            consent_version: string | null;
            /** Csrf Token */
            csrf_token: string;
        };
        /**
         * MePatch
         * @description Lista explícita de campos editables por el alumno.
         */
        MePatch: {
            /** Display Name */
            display_name?: string | null;
            /** Timezone */
            timezone?: string | null;
            /** Goal Purpose */
            goal_purpose?: ("work" | "studies" | "certification" | "other" | "unknown") | null;
            /** Target Exam */
            target_exam?: ("toefl_ibt" | "ielts_academic" | "cambridge_b2_first" | "toefl_itp" | "other" | "unknown") | null;
            /** Target Exam Other */
            target_exam_other?: string | null;
            /** Target Score */
            target_score?: string | null;
            /** Target Date */
            target_date?: string | null;
            /** Self Reported Level */
            self_reported_level?: ("A2" | "B1" | "B2" | "unknown") | null;
            /** Onboarded */
            onboarded?: boolean | null;
        };
        /** PassageOut */
        PassageOut: {
            /** Id */
            id: string;
            /** Title En */
            title_en?: string | null;
            /** Text En */
            text_en: string;
        };
        /** PathOut */
        PathOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Code */
            code: string;
            /** Title */
            title: string;
            /** Label */
            label: string;
        };
        /** PathStateOut */
        PathStateOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Code */
            code: string;
            /** Title */
            title: string;
            /** Label */
            label: string;
            /** Units */
            units: components["schemas"]["UnitStateOut"][];
            /** Assessments */
            assessments: components["schemas"]["ItemStateRefOut"][];
        };
        /** PcreOut */
        PcreOut: {
            /** Pattern */
            pattern: string;
            /** Concept */
            concept: string;
            /** Rules */
            rules: components["schemas"]["PcreRuleOut"][];
            /** Examples */
            examples: string[];
        };
        /** PcreRuleOut */
        PcreRuleOut: {
            /** Text */
            text: string;
            /** Source */
            source?: string | null;
            /** Applies When Not Es */
            applies_when_not_es?: string | null;
        };
        /** ProgressOut */
        ProgressOut: {
            /** Started At */
            started_at: string | null;
            /** Completed At */
            completed_at: string | null;
        };
        /** PublishIn */
        PublishIn: {
            /** Note */
            note?: string | null;
        };
        /** PublishedOut */
        PublishedOut: {
            /**
             * Revision Id
             * Format: uuid
             */
            revision_id: string;
            /** Item Slug */
            item_slug: string;
            /** Version */
            version: number;
        };
        /** ReadyOut */
        ReadyOut: {
            /** Status */
            status: string;
            /** Migration */
            migration: string;
        };
        /** ResetConfirmIn */
        ResetConfirmIn: {
            /** Token */
            token: string;
            /** Password */
            password: string;
            /** Password Confirm */
            password_confirm: string;
        };
        /** ResetInfoOut */
        ResetInfoOut: {
            /** Email */
            email: string;
        };
        /** RevisionDetailOut */
        RevisionDetailOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Item */
            item: {
                [key: string]: unknown;
            };
            /** Version */
            version: number;
            /** Status */
            status: string;
            /** File Status */
            file_status: string;
            /** Content Hash */
            content_hash: string;
            /** Approved Hash */
            approved_hash: string | null;
            /** Approved At */
            approved_at: string | null;
            /** Published At */
            published_at: string | null;
            /** Withdrawn At */
            withdrawn_at: string | null;
            /** Withdraw Reason */
            withdraw_reason: string | null;
            /** Source Path */
            source_path: string;
            /** Source Commit */
            source_commit: string | null;
            /** Lint Errors */
            lint_errors: number;
            /** Lint Warnings */
            lint_warnings: {
                [key: string]: unknown;
            }[];
            /** Audio Pending */
            audio_pending: boolean;
            /** Body */
            body: {
                [key: string]: unknown;
            };
            /** Activities */
            activities: {
                [key: string]: unknown;
            }[];
            /** Sources */
            sources: {
                [key: string]: unknown;
            }[];
            /** Findings */
            findings: components["schemas"]["FindingOut"][];
            /** Decisions */
            decisions: {
                [key: string]: unknown;
            }[];
            /** Checklist */
            checklist: string[];
            /** Preview Practice */
            preview_practice: {
                [key: string]: unknown;
            };
            /** Preview Assessment */
            preview_assessment: {
                [key: string]: unknown;
            };
            /** Blockers */
            blockers: {
                [key: string]: string[];
            };
        };
        /** RevisionRowOut */
        RevisionRowOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Item Id
             * Format: uuid
             */
            item_id: string;
            /** Item Slug */
            item_slug: string;
            /** Item Title */
            item_title: string;
            /** Kind */
            kind: string;
            /** Skill */
            skill: string | null;
            /** Form Kind */
            form_kind: string | null;
            /** Unit */
            unit: {
                [key: string]: unknown;
            } | null;
            /** Version */
            version: number;
            /** Status */
            status: string;
            /** File Status */
            file_status: string;
            /** Content Hash */
            content_hash: string;
            /** Is Published */
            is_published: boolean;
            /** Warnings */
            warnings: number;
            /** Audio Pending */
            audio_pending: boolean;
            /** Open Material Findings */
            open_material_findings: number;
            /** Created At */
            created_at: string;
        };
        /**
         * SelfAssessmentIn
         * @description Marca de 0 a 3 por criterio de la rúbrica, enviada después de ver la rúbrica.
         */
        SelfAssessmentIn: {
            /** Scores */
            scores: {
                [key: string]: number;
            };
        };
        /** StimulusOut */
        StimulusOut: {
            /** Text En */
            text_en?: string | null;
            /** Passage */
            passage?: string | null;
            /** Audio Url */
            audio_url?: string | null;
            /**
             * Has Audio
             * @default false
             */
            has_audio: boolean;
        };
        /** StudentActivityOut */
        StudentActivityOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Key */
            key: string;
            /** Position */
            position: number;
            /**
             * Format
             * @enum {string}
             */
            format: "choice" | "word_completion" | "sentence_order" | "short_writing" | "recorded_speaking" | "guided_dialogue";
            /** Task Family */
            task_family: string;
            /**
             * Pool
             * @enum {string}
             */
            pool: "practice" | "review" | "assessment";
            /** Objectives */
            objectives: string[];
            /** Instructions Es */
            instructions_es: string;
            /** Prompt En */
            prompt_en: string;
            stimulus: components["schemas"]["StimulusOut"] | null;
            /** Data */
            data: {
                [key: string]: unknown;
            };
            /** Aids */
            aids: components["schemas"]["AidOut"][];
        };
        /** TokenIn */
        TokenIn: {
            /** Token */
            token: string;
        };
        /** UnitRefOut */
        UnitRefOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Position */
            position: number;
        };
        /** UnitStateOut */
        UnitStateOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Position */
            position: number;
            /** Items */
            items: components["schemas"]["ItemStateRefOut"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WithdrawIn */
        WithdrawIn: {
            /** Reason */
            reason: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    ready_api_v1_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyOut"];
                };
            };
        };
    };
    inspect_invitation_api_v1_auth_invitations_inspect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationInfoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_invitation_api_v1_auth_invitations_accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptInvitationIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    inspect_reset_api_v1_auth_password_reset_inspect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetInfoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_reset_api_v1_auth_password_reset_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetConfirmIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    delete_me_api_v1_me_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteMeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_me_api_v1_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_me_api_v1_me_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    admin_list_users_api_v1_admin_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserOut"][];
                };
            };
        };
    };
    admin_invite_api_v1_admin_invitations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminInvitationIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_reset_link_api_v1_admin_users__user_id__reset_link_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_revoke_sessions_api_v1_admin_users__user_id__revoke_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_patch_user_api_v1_admin_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminUserPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_api_v1_content_reports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContentReportIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_paths_api_v1_learning_paths_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PathOut"][];
                };
            };
        };
    };
    path_detail_api_v1_learning_paths__path_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PathStateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lesson_api_v1_lessons__item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scenario_api_v1_scenarios__item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    serve_aid_api_v1_aids_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AidIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AidContentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_attempt_api_v1_attempts_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttemptIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttemptOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    self_assess_api_v1_attempts__attempt_id__self_assessment_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SelfAssessmentIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttemptDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_attempt_api_v1_attempts__attempt_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttemptDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_attempts_api_v1_me_attempts_get: {
        parameters: {
            query?: {
                limit?: number;
                before?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttemptSummaryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_revisions_api_v1_admin_content_revisions_get: {
        parameters: {
            query?: {
                kind?: string | null;
                status?: string | null;
                unit_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionRowOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_units_api_v1_admin_content_units_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUnitOut"][];
                };
            };
        };
    };
    revision_detail_api_v1_admin_content_revisions__revision_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                revision_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_finding_api_v1_admin_content_revisions__revision_id__findings_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                revision_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FindingIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_finding_api_v1_admin_content_findings__finding_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                finding_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FindingPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_api_v1_admin_content_revisions__revision_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                revision_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_api_v1_admin_content_revisions__revision_id__publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                revision_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_unit_api_v1_admin_content_units__unit_id__publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                unit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishedOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    withdraw_api_v1_admin_content_revisions__revision_id__withdraw_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                revision_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WithdrawIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
